# Generated by Django 3.0.5 on 2020-05-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjFiles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.FileField(upload_to='')),
            ],
        ),
    ]
