# Generated by Django 3.0.5 on 2020-05-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0002_djfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djfiles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
