# Generated by Django 3.0.8 on 2021-01-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfinances', '0003_auto_20200504_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='date_of_expense',
            new_name='dateOfExpense',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='date_of_upload',
            new_name='dateOfUpload',
        ),
    ]
